"use client";

import { useState, useEffect } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { DashboardLayout } from "@/components/Layout/DashboardLayout";
import { Card } from "@/components/ui/Card";
import { useCreateStudent } from "@/hooks/api/useStudents";
import { useCourses } from "@/hooks/api/useCourses";
import { useUniversities } from "@/hooks/api/useUniversities";
import { GraduationCap, Save, X } from "lucide-react";
import { toast } from "sonner";

export default function NewStudentPage() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const createStudent = useCreateStudent();
  const { data: courses } = useCourses();
  const { data: universities } = useUniversities();

  const [formData, setFormData] = useState({
    firstName: "",
    lastName: "",
    email: "",
    fatherName: "",
    address: "",
    contactNumber: "",
    whatsappNumber: "",
    qualification: "",
    mainSubject: "",
    enquiryDate: "",
    dateOfBirth: "",
    gender: "male",
    course: "",
    medium: "",
    university: "",
    session: "",
    sessionMonth: "",
    yearOfPassing: "",
    division: "",
    percentageOfMarks: "",
    boardOrUniversity: "",
    category: "",
    addharNo: "",
    familyIncome: "",
    religion: "",
    maritalStatus: "",
    enquiryBy: "",
    joiningDate: "",
    reference: "",
    registrationPaymentMode: "Cash",
    installment: "",
    due: "",
    registrationPayment: "Done",
    dueDate: "",
  });

  // Pre-fill form from query parameters (from inquiry)
  useEffect(() => {
    if (searchParams) {
      setFormData((prev) => ({
        ...prev,
        firstName: searchParams.get("firstName") || prev.firstName,
        lastName: searchParams.get("lastName") || prev.lastName,
        email: searchParams.get("email") || prev.email,
        fatherName: searchParams.get("fatherName") || prev.fatherName,
        contactNumber: searchParams.get("contactNumber") || prev.contactNumber,
        qualification: searchParams.get("qualification") || prev.qualification,
        address: searchParams.get("address") || prev.address,
        course: searchParams.get("course") || prev.course,
      }));
    }
  }, [searchParams]);

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      // R_no will be auto-generated by the backend
      await createStudent.mutateAsync(formData);
      toast.success("Student registered successfully");
      router.push("/students");
    } catch (error) {
      toast.error(
        error.response?.data?.message || "Failed to register student"
      );
    }
  };

  const handleChange = (e) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  // Generate session years
  const sessions = [];
  const currentYear = new Date().getFullYear();
  for (let i = 0; i < 12; i++) {
    const year = currentYear + i;
    sessions.push(`${year}-${year + 1}`);
  }

  const months = [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
  ];

  return (
    <DashboardLayout>
      <div className="space-y-6">
        {/* Page Header */}
        <div className="bg-primary rounded-lg p-6 text-white">
          <h1 className="text-2xl font-bold flex items-center gap-2">
            <GraduationCap className="w-6 h-6" />
            Student Registration Form
          </h1>
          <p className="text-primary-100">
            MAA Computers &gt; Students &gt; New Registration
          </p>
        </div>

        <form onSubmit={handleSubmit} className="space-y-6">
          {/* Basic Information */}
          <Card>
            <h2 className="text-lg font-semibold mb-4 text-gray-800">
              Basic Information
            </h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {/* Student Name */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Student Name <span className="text-red-500">*</span>
                </label>
                <input
                  type="text"
                  name="firstName"
                  value={formData.firstName}
                  onChange={handleChange}
                  required
                  placeholder="Enter First Name"
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent"
                />
              </div>

              {/* Student Surname */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Student Surname <span className="text-red-500">*</span>
                </label>
                <input
                  type="text"
                  name="lastName"
                  value={formData.lastName}
                  onChange={handleChange}
                  required
                  placeholder="Enter Last Name"
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent"
                />
              </div>

              {/* Email */}
              <div className="md:col-span-2">
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Student Email <span className="text-red-500">*</span>
                </label>
                <input
                  type="email"
                  name="email"
                  value={formData.email}
                  onChange={handleChange}
                  required
                  placeholder="Enter Email Address"
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent"
                />
              </div>

              {/* Father/Husband Name */}
              <div className="md:col-span-12">
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Name of Father / Husband{" "}
                  <span className="text-red-500">*</span>
                </label>
                <input
                  type="text"
                  name="fatherName"
                  value={formData.fatherName}
                  onChange={handleChange}
                  required
                  placeholder="Enter Name Of Father / Husband"
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent"
                />
              </div>

              {/* Address */}
              <div className="md:col-span-12">
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Permanent Address <span className="text-red-500">*</span>
                </label>
                <input
                  type="text"
                  name="address"
                  value={formData.address}
                  onChange={handleChange}
                  required
                  placeholder="Enter Your Permanent Address"
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent"
                />
              </div>

              {/* Contact Number */}
              <div className="md:col-span-6">
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Contact Number <span className="text-red-500">*</span>
                </label>
                <input
                  type="tel"
                  name="contactNumber"
                  value={formData.contactNumber}
                  onChange={handleChange}
                  required
                  placeholder="Enter Contact Number"
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent"
                />
              </div>

              {/* WhatsApp Number */}
              <div className="md:col-span-6">
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  WhatsApp Number <span className="text-red-500">*</span>
                </label>
                <input
                  type="tel"
                  name="whatsappNumber"
                  value={formData.whatsappNumber}
                  onChange={handleChange}
                  required
                  placeholder="Enter WhatsApp Number"
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent"
                />
              </div>

              {/* Qualification */}
              <div className="md:col-span-6">
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Qualification <span className="text-red-500">*</span>
                </label>
                <input
                  type="text"
                  name="qualification"
                  value={formData.qualification}
                  onChange={handleChange}
                  required
                  placeholder="Enter Qualification"
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent"
                />
              </div>

              {/* Main Subject */}
              <div className="md:col-span-2">
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Main Subject <span className="text-red-500">*</span>
                </label>
                <input
                  type="text"
                  name="mainSubject"
                  value={formData.mainSubject}
                  onChange={handleChange}
                  required
                  placeholder="Main Subject"
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent"
                />
              </div>

              {/* Enquiry Date */}
              <div className="md:col-span-2">
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Enquiry Date <span className="text-red-500">*</span>
                </label>
                <input
                  type="date"
                  name="enquiryDate"
                  value={formData.enquiryDate}
                  onChange={handleChange}
                  required
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent"
                />
              </div>

              {/* Date of Birth */}
              <div className="md:col-span-2">
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Date Of Birth <span className="text-red-500">*</span>
                </label>
                <input
                  type="date"
                  name="dateOfBirth"
                  value={formData.dateOfBirth}
                  onChange={handleChange}
                  required
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent"
                />
              </div>

              {/* Gender */}
              <div className="md:col-span-12">
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Gender <span className="text-red-500">*</span>
                </label>
                <div className="flex gap-6">
                  <label className="flex items-center gap-2 cursor-pointer">
                    <input
                      type="radio"
                      name="gender"
                      value="male"
                      checked={formData.gender === "male"}
                      onChange={handleChange}
                      className="w-4 h-4 text-primary focus:ring-primary"
                    />
                    <span className="text-gray-700">Male</span>
                  </label>
                  <label className="flex items-center gap-2 cursor-pointer">
                    <input
                      type="radio"
                      name="gender"
                      value="female"
                      checked={formData.gender === "female"}
                      onChange={handleChange}
                      className="w-4 h-4 text-primary focus:ring-primary"
                    />
                    <span className="text-gray-700">Female</span>
                  </label>
                </div>
              </div>
            </div>
          </Card>

          {/* Course & Academic Information */}
          <Card>
            <h2 className="text-lg font-semibold mb-4 text-gray-800">
              Course & Academic Information
            </h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {/* Select Course */}
              <div className="md:col-span-2">
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Select Course <span className="text-red-500">*</span>
                </label>
                <select
                  name="course"
                  value={formData.course}
                  onChange={handleChange}
                  required
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent"
                >
                  <option value="">Choose a course...</option>
                  {courses?.map((course) => (
                    <option key={course._id} value={course._id}>
                      {course.courseName}
                    </option>
                  ))}
                </select>
              </div>

              {/* Medium */}
              <div className="md:col-span-2">
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Medium <span className="text-red-500">*</span>
                </label>
                <select
                  name="medium"
                  value={formData.medium}
                  onChange={handleChange}
                  required
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent"
                >
                  <option value="">Choose Medium...</option>
                  <option value="english">English Medium</option>
                  <option value="hindi">Hindi Medium</option>
                </select>
              </div>

              {/* Select University */}
              <div className="md:col-span-2">
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Select University <span className="text-red-500">*</span>
                </label>
                <select
                  name="university"
                  value={formData.university}
                  onChange={handleChange}
                  required
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent"
                >
                  <option value="">Choose a University...</option>
                  {universities?.map((university) => (
                    <option key={university._id} value={university.name}>
                      {university.name} {university.location}
                    </option>
                  ))}
                </select>
              </div>

              {/* Session */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Session <span className="text-red-500">*</span>
                </label>
                <select
                  name="session"
                  value={formData.session}
                  onChange={handleChange}
                  required
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent"
                >
                  <option value="">Choose a Session...</option>
                  {sessions.map((session) => (
                    <option key={session} value={session}>
                      {session}
                    </option>
                  ))}
                </select>
              </div>

              {/* Session Month */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Session Month <span className="text-red-500">*</span>
                </label>
                <select
                  name="sessionMonth"
                  value={formData.sessionMonth}
                  onChange={handleChange}
                  required
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent"
                >
                  <option value="">Choose a Session Month...</option>
                  {months.map((month) => (
                    <option key={month} value={month}>
                      {month}
                    </option>
                  ))}
                </select>
              </div>

              {/* Year of Passing */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Year of Passing <span className="text-red-500">*</span>
                </label>
                <input
                  type="number"
                  name="yearOfPassing"
                  value={formData.yearOfPassing}
                  onChange={handleChange}
                  required
                  placeholder="e.g. 2023"
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent"
                />
              </div>

              {/* Division */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Division <span className="text-red-500">*</span>
                </label>
                <select
                  name="division"
                  value={formData.division}
                  onChange={handleChange}
                  required
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent"
                >
                  <option value="">Select</option>
                  <option value="1">1st Division</option>
                  <option value="2">2nd Division</option>
                  <option value="3">3rd Division</option>
                  <option value="4">Pass</option>
                </select>
              </div>

              {/* % of Marks */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  % of Marks <span className="text-red-500">*</span>
                </label>
                <input
                  type="number"
                  step="0.01"
                  name="percentageOfMarks"
                  value={formData.percentageOfMarks}
                  onChange={handleChange}
                  required
                  placeholder="e.g. 75.50"
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent"
                />
              </div>

              {/* Board/University */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Board/University <span className="text-red-500">*</span>
                </label>
                <input
                  type="text"
                  name="boardOrUniversity"
                  value={formData.boardOrUniversity}
                  onChange={handleChange}
                  required
                  placeholder="e.g. CBSE, RGPV"
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent"
                />
              </div>
            </div>
          </Card>

          {/* Personal & Additional Information */}
          <Card>
            <h2 className="text-lg font-semibold mb-4 text-gray-800">
              Personal & Additional Information
            </h2>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              {/* Category (Caste) */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Category (Caste) <span className="text-red-500">*</span>
                </label>
                <select
                  name="category"
                  value={formData.category}
                  onChange={handleChange}
                  required
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent"
                >
                  <option value="">Choose Caste...</option>
                  <option value="SC">Scheduled Castes (SC)</option>
                  <option value="ST">Scheduled Tribes (ST)</option>
                  <option value="OBC">Other Backward Classes (OBC)</option>
                  <option value="General">General</option>
                </select>
              </div>

              {/* UID Number */}
              <div className="md:col-span-2">
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  UID Number (Aadhaar) <span className="text-red-500">*</span>
                </label>
                <input
                  type="text"
                  name="addharNo"
                  value={formData.addharNo}
                  onChange={handleChange}
                  required
                  placeholder="Enter UID Number"
                  maxLength="12"
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent"
                />
              </div>

              {/* Family Income */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Family Income (Yearly) <span className="text-red-500">*</span>
                </label>
                <input
                  type="number"
                  name="familyIncome"
                  value={formData.familyIncome}
                  onChange={handleChange}
                  required
                  placeholder="e.g. 500000"
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent"
                />
              </div>

              {/* Religion */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Religion <span className="text-red-500">*</span>
                </label>
                <select
                  name="religion"
                  value={formData.religion}
                  onChange={handleChange}
                  required
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent"
                >
                  <option value="">Select Religion</option>
                  <option value="Hindu">Hindu</option>
                  <option value="Muslim">Muslim</option>
                  <option value="Christian">Christian</option>
                  <option value="Sikh">Sikh</option>
                  <option value="Buddhist">Buddhist</option>
                  <option value="Jain">Jain</option>
                  <option value="Other">Other</option>
                </select>
              </div>

              {/* Marital Status */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Marital Status <span className="text-red-500">*</span>
                </label>
                <select
                  name="maritalStatus"
                  value={formData.maritalStatus}
                  onChange={handleChange}
                  required
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent"
                >
                  <option value="">Select Status</option>
                  <option value="Single">Single</option>
                  <option value="Married">Married</option>
                  <option value="Widowed">Widowed</option>
                  <option value="Divorced">Divorced</option>
                </select>
              </div>

              {/* Enquiry By */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Enquiry By <span className="text-red-500">*</span>
                </label>
                <input
                  type="text"
                  name="enquiryBy"
                  value={formData.enquiryBy}
                  onChange={handleChange}
                  required
                  placeholder="Enter Name"
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent"
                />
              </div>

              {/* Like To Join */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Like To Join <span className="text-red-500">*</span>
                </label>
                <input
                  type="date"
                  name="joiningDate"
                  value={formData.joiningDate}
                  onChange={handleChange}
                  required
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent"
                />
              </div>

              {/* You Came To Know About Institute By */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  You Came To Know About Institute By:
                </label>
                <select
                  name="reference"
                  value={formData.reference}
                  onChange={handleChange}
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent"
                >
                  <option value="">Choose...</option>
                  <option value="Sign Board">Sign Board</option>
                  <option value="Advertisement Papers">
                    Advertisement Papers
                  </option>
                  <option value="Google Search">Google Search</option>
                  <option value="Instagram">Instagram</option>
                  <option value="Facebook">Facebook</option>
                  <option value="Personal Reference">Personal Reference</option>
                  <option value="Other">Other</option>
                </select>
              </div>
            </div>
          </Card>

          {/* Payment Information */}
          <Card>
            <h2 className="text-lg font-semibold mb-4 text-gray-800">
              Payment Information
            </h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {/* Registration Payment Mode */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Registration Payment Mode:
                </label>
                <select
                  name="registrationPaymentMode"
                  value={formData.registrationPaymentMode}
                  onChange={handleChange}
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent"
                >
                  <option value="Cash">Cash</option>
                  <option value="Phone pe">Phone pe</option>
                  <option value="Google pay">Google pay</option>
                  <option value="Cheque">Cheque</option>
                </select>
              </div>

              {/* Registration Payment */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Registration Payment:
                </label>
                <select
                  name="registrationPayment"
                  value={formData.registrationPayment}
                  onChange={handleChange}
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent"
                >
                  <option value="Done">Done</option>
                  <option value="Not Done">Not Done</option>
                </select>
              </div>

              {/* Installment */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Installment <span className="text-red-500">*</span>
                </label>
                <input
                  type="number"
                  name="installment"
                  value={formData.installment}
                  onChange={handleChange}
                  required
                  placeholder="Enter Installment Amount"
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent"
                />
              </div>

              {/* Due */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Due <span className="text-red-500">*</span>
                </label>
                <input
                  type="number"
                  name="due"
                  value={formData.due}
                  onChange={handleChange}
                  required
                  placeholder="Enter Due Amount"
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent"
                />
              </div>

              {/* Due Amount Date */}
              <div className="md:col-span-2">
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Due Amount Date <span className="text-red-500">*</span>
                </label>
                <input
                  type="date"
                  name="dueDate"
                  value={formData.dueDate}
                  onChange={handleChange}
                  required
                  placeholder="Enter Due Amount date"
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent"
                />
              </div>
            </div>
          </Card>

          {/* Action Buttons */}
          <Card>
            <div className="flex justify-end gap-4">
              <button
                type="button"
                onClick={() => router.push("/students")}
                className="px-6 py-2 border border-gray-300 rounded-lg text-gray-700 hover:bg-gray-50 transition-colors flex items-center gap-2"
              >
                <X className="w-4 h-4" />
                Cancel
              </button>
              <button
                type="submit"
                disabled={createStudent.isPending}
                className="px-6 py-2 bg-primary text-white rounded-lg hover:bg-primary-dark transition-colors flex items-center gap-2 disabled:opacity-50"
              >
                <Save className="w-4 h-4" />
                {createStudent.isPending
                  ? "Registering..."
                  : "Register Student"}
              </button>
            </div>
          </Card>
        </form>
      </div>
    </DashboardLayout>
  );
}
